#!/bin/sh
set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIR="${SCRIPT_DIR}/../"
cd "${PROJECT_DIR}"
sourcery --sources ./NewsAPIKit/NewsAPIKit --sources ./NewsApp --templates ./NewsAPIKit/NewsAPIKitTests/Mocks/Templates --output ./NewsAPIKit/NewsAPIKitTests/Mocks/Autogenerated
sourcery --sources ./NewsAPIKit/NewsAPIKit --sources ./NewsApp --templates ./NewsAppTests/Mocks/Templates --output ./NewsAppTests/Mocks/Autogenerated
sourcery --sources ./NewsAPIKit/NewsAPIKit --sources ./NewsApp --templates ./NewsAppTests/Mocks/Templates --output ./NewsAppUITests/Mocks/Autogenerated
